// Actual HTTP/PostgreSQL/worker/Firefox suite. Real AI is explicitly opt-in.
// Use scripts/curation-step3-review.py with a dedicated, synthetic-only DB.
const { firefox } = require('playwright');
const fs = require('node:fs/promises');
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const base = process.env.E2E_BASE_URL || 'http://127.0.0.1:18083';
const out = process.env.E2E_SCREENSHOT_DIR || '/tmp/vitlane-step3-review';
if (process.env.E2E_LIVE_AI !== '1' || !['localhost', '127.0.0.1'].includes(new URL(base).hostname)) {
  throw new Error('Requires E2E_LIVE_AI=1 and a dedicated localhost review server; AI calls incur usage.');
}
async function initialScenario() {
const browser=await firefox.launch();const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>console.log('pageerror',e.message));
try {
let r=await context.request.post(base+'/api/v1/dev/auth/session',{data:{profileKey:'multi-product'}});console.log('login',r.status());assert.equal(r.status(),201);
await fs.mkdir(out,{recursive:true});const preferences=await(await context.request.get(base+'/api/v1/me/preferences')).json();await context.request.patch(base+'/api/v1/me/preferences',{data:{schemaVersion:'vitlane.user-preferences.v1',expectedVersion:preferences.preferences.version,uiLocale:'ko-KR',preferredCurrency:'USD',researchCountry:'US'}});
const cap=await(await context.request.get(base+'/api/v1/managed-runner/capability')).json();console.log('AI enabled',cap.enabled);assert(cap.enabled);
r=await context.request.post(base+'/api/v1/shopping-plans',{headers:{'Idempotency-Key':randomUUID()},data:{originalIntent:'만년필과 잉크 추천',planningMode:'AUTO',executionMode:'EXPERIMENT',budget:{schemaVersion:'vitlane.curation-budget.v1',currency:'USD',totalAmount:'150.00',allocationMode:'AUTO'},location:{country:'US',city:''},category:'',allowedItems:[],blockedItems:[],minPrice:null,maxPrice:null,referenceUrl:'',urlMode:'NONE',agentMode:'MANAGED',modelKey:cap.defaultModelKey}});
const created=await r.json();console.log('create',r.status(),created.error||created.curation?.id);assert.equal(r.status(),201);const id=created.curation.id;await fs.writeFile(out+'/curation-id',id);await page.goto(base+'/curations/'+id);
let w;for(let i=0;i<90;i++){w=await(await context.request.get(base+`/api/v1/curations/${id}/workspace`)).json();if(i%5===0)console.log('progress',w.curation?.phase,w.targets?.length,w.activeWork?.status,w.intelligenceJobs?.map(j=>({status:j.status,reason:j.reasonCode})));if(w.targets?.length>=2&&!w.activeWork)break;await page.waitForTimeout(2000);}
await fs.writeFile(out+'/initial-workspace.json',JSON.stringify(w,null,2));const budget=await(await context.request.get(base+`/api/v1/curations/${id}/budget`)).json();await fs.writeFile(out+'/initial-budget.json',JSON.stringify(budget,null,2));console.log('budget',JSON.stringify(budget));console.log('sources',w.catalogResearch?.pools?.map(p=>p.products.map(x=>x.source)));await page.reload();await page.waitForTimeout(1500);await page.screenshot({path:out+'/initial-desktop.png',fullPage:true});assert.equal(w.targets.length,2);assert(w.research.groups.every(g=>g.round.status==='RESULTS_READY'));assert(w.catalogResearch.pools.every(p=>p.products.length>0));assert.equal(budget.totalAmount,'150.00');
console.log('PASS initial real AI allocation',base+'/curations/'+id);
}finally{await browser.close();}
}

async function budgetEditing() {
const browser=await firefox.launch();const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.setDefaultTimeout(18000);const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
assert.equal((await context.request.post(base+'/api/v1/dev/auth/session',{data:{profileKey:'multi-product'}})).status(),201);const id=(await fs.readFile(out+'/curation-id','utf8')).trim();const url=base+'/curations/'+id,path=base+`/api/v1/curations/${id}/budget`;
const read=async()=>await(await context.request.get(path)).json();const work=async()=>await(await context.request.get(base+`/api/v1/curations/${id}/workspace`)).json();
const stable=w=>JSON.stringify({targets:w.targets.map(t=>[t.id,t.targetHash]),research:w.research,pools:w.catalogResearch.pools.map(p=>({target:p.targetId,version:p.version,candidates:p.products.map(c=>c.candidateId)})),configurations:w.catalogResearch.configurations,interactions:w.catalogResearch.interactions});
await page.goto(url);await page.locator('.curation-budget__heading button').first().waitFor();let before=await read();let workspace=await work();const original=stable(workspace);assert(workspace.catalogResearch.pools.length>0);
await page.locator('.curation-budget__heading button').first().click();await page.getByLabel('총 예산',{exact:true}).fill('900.00');await page.getByRole('button',{name:'배분하기',exact:true}).click();await page.getByRole('button',{name:'수동 배분',exact:true}).click();await page.getByRole('button',{name:'취소',exact:true}).click();assert.deepEqual(await read(),before);console.log('PASS total draft cancel');
await page.locator('.curation-budget__segment').first().click();await page.getByLabel('Target 예산',{exact:true}).fill('120.00');await page.getByLabel('목표 수량',{exact:true}).fill('2');await page.getByLabel('개당 하한',{exact:true}).fill('10.00');await page.screenshot({path:out+'/target-budget-dialog.png'});await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});let edited=await read();assert.equal(edited.allocations[0].amount,'120.00');assert.equal(edited.allocations[0].quantity,2);assert.deepEqual(edited.allocations[1],before.allocations[1]);assert.equal(stable(await work()),original);console.log('PASS target amount + quantity; other targets and candidates preserved');
const command={schemaVersion:'vitlane.curation-budget.v1',commandId:randomUUID(),expectedVersion:edited.version,kind:'SET_MINIMUM',targetId:edited.allocations[0].targetId,minimumUnitAmount:'11.00'};let resp=await context.request.patch(path,{data:command});assert.equal(resp.status(),200);let floor=await resp.json();assert.equal(floor.researchVersion,edited.researchVersion);assert.deepEqual(await(await context.request.patch(path,{data:command})).json(),floor);console.log('PASS floor only and idempotent replay');
await page.reload();await page.locator('.curation-budget__heading button').first().click();await page.getByRole('button',{name:'제한 없음으로 변경',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});let disabled=await read();assert.equal(disabled.enabled,false);assert.equal(disabled.allocations[0].quantity,2);assert(await page.locator('.curation-budget__bar').isVisible());assert.equal(stable(await work()),original);console.log('PASS disable retains bar and candidates');
await page.locator('.curation-budget__heading button').first().click();await page.getByLabel('총 예산',{exact:true}).fill('200.00');await page.getByRole('button',{name:'배분하기',exact:true}).click();await page.getByRole('button',{name:'수동 배분',exact:true}).waitFor({state:'visible'});await page.getByRole('button',{name:'수동 배분',exact:true}).click();const inputs=page.locator('.budget-editor__allocations input');await inputs.nth(0).fill('120.00');await inputs.nth(1).fill('90.00');assert(await page.getByRole('button',{name:'저장',exact:true}).isDisabled());await inputs.nth(1).fill('80.00');await page.screenshot({path:out+'/manual-allocation.png'});await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});let active=await read();assert.equal(active.totalAmount,'200.00');assert.equal(active.allocations[0].quantity,2);assert.equal(active.allocations[0].minimumUnitAmount,undefined);assert.equal(stable(await work()),original);console.log('PASS reenable manual exact allocation; no historical restore');
await page.locator('.catalog-ui-focus-token').click();await page.getByRole('option').filter({hasText:'상품 추가'}).click();await page.getByLabel('조사 요청',{exact:true}).fill('노이즈 캔슬링 헤드폰을 추가해줘. 총예산은 1달러로 바꿔.');await page.getByRole('button',{name:'조사 요청 보내기',exact:true}).click();let added;for(let i=0;i<90;i++){added=await work();if(added.targets.length===3&&added.research.groups.length===3&&added.research.groups.every(g=>['RESULTS_READY','NO_RESULTS','FAILED'].includes(g.round?.status))&&!added.activeWork)break;await page.waitForTimeout(1500);}let afterAdd=await read();await fs.writeFile(out+'/added-workspace.json',JSON.stringify(added,null,2));assert.equal(added.targets.length,3);assert.deepEqual(afterAdd.allocations.slice(0,2),active.allocations);assert.equal(afterAdd.totalAmount,active.totalAmount);assert.equal(afterAdd.allocations.at(-1).amount,"0.00");console.log('PASS real AI Target add',afterAdd.totalAmount,added.catalogResearch.pools.map(p=>p.products.map(x=>x.source)));assert(added.catalogResearch.pools.some(p=>p.products.some(x=>x.source==='AMAZON')),'Amazon stub candidate expected after headphones addition');
await page.reload();await page.screenshot({path:out+'/budget-desktop.png',fullPage:true});await fs.writeFile(out+'/ui-result.json',JSON.stringify({id,errors,originalBudget:before,afterAddBudget:afterAdd,checks:['cancel','atomic_target','floor_view_only','replay','disable','manual_reenable','existing_candidates','ai_add','amazon_stub']},null,2));assert.deepEqual(errors,[]);console.log('PASS UI and real AI additions',url);
}finally{await browser.close();}
}

async function researchAndCart() {
const browser=await firefox.launch();const c=await browser.newContext({viewport:{width:1440,height:1000}});const page=await c.newPage();page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
await c.request.post(base+'/api/v1/dev/auth/session',{data:{profileKey:'multi-product'}});const id=(await fs.readFile(out+'/curation-id','utf8')).trim(),url=base+'/curations/'+id,bp=base+`/api/v1/curations/${id}/budget`;const work=async()=>await(await c.request.get(base+`/api/v1/curations/${id}/workspace`)).json();const budget=async()=>await(await c.request.get(bp)).json();let ledger=await budget();const pen=ledger.allocations[0].targetId;
async function patch(fields){ledger=await budget();const r=await c.request.patch(bp,{data:{schemaVersion:ledger.schemaVersion,commandId:randomUUID(),expectedVersion:ledger.version,...fields}});const b=await r.json();assert.equal(r.status(),200,JSON.stringify(b));ledger=b;return b;}
await page.goto(url);await page.locator('.curation-budget__heading button').first().waitFor();
// Simulate losing a successful response; the UI retries the same command.
let dropped=false;const commands=[];await page.route('**/budget',async route=>{if(route.request().method()!=='PATCH')return route.continue();commands.push(route.request().postDataJSON());if(!dropped){dropped=true;const r=await route.fetch();assert.equal(r.status(),200);await route.abort('failed');}else await route.continue();});
await page.locator('.curation-budget__segment').first().click();await page.getByLabel('Target 예산',{exact:true}).fill('120.02');await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('button',{name:'저장 다시 확인',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.deepEqual(commands[0],commands[1]);await page.unroute('**/budget');assert.equal((await budget()).allocations[0].amount,'120.02');
await patch({kind:'SET_TARGET',targetId:pen,amount:'1.00',quantity:2,updateMinimum:true});await page.reload();const first=page.locator('.catalog-ui-target').first();await first.locator('.budget-delta.is-over').first().waitFor();await first.getByRole('button',{name:'장바구니 담기',exact:true}).first().click();const dialog=page.getByRole('dialog');await dialog.waitFor();await dialog.getByRole('button',{name:'장바구니 담기',exact:true}).click();await dialog.waitFor({state:'hidden'});
await page.locator('.catalog-ui-draft-trigger').click();await page.locator('.budget-cart-summary').waitFor();console.log('cart',await page.locator('.budget-cart-summary').innerText());await page.locator('.catalog-ui-draft-drawer select').first().selectOption('3');await page.waitForTimeout(500);await page.screenshot({path:out+'/cart-budget.png'});const cart=await(await c.request.get(base+`/api/v1/curations/${id}/cart`)).json();const sum=cart.items.reduce((total,item)=>total+item.previewPriceMinor*item.quantity,0);const savings=Math.round(Number((await budget()).totalAmount)*100)-sum;assert((await page.locator('.budget-cart-summary').innerText()).includes('$'+(savings/100).toFixed(2)));await fs.writeFile(out+'/cart.json',JSON.stringify(cart,null,2));await page.getByRole('button',{name:'장바구니 닫기',exact:true}).click();console.log('PASS over-budget candidate actions and cart quantity');
// New Round: cap 30 / 2 = 15 USD; earlier candidate state persisted before research.
await patch({kind:'SET_TARGET',targetId:pen,amount:'30.00',quantity:2,updateMinimum:true,minimumUnitAmount:'14.00'});await page.reload();let before=await work();const prev=before.research.groups.find(g=>g.target?.id===pen||g.targetId===pen)?.round?.roundNumber??before.research.groups[0].round.roundNumber;await page.locator('.catalog-ui-focus-token').click();await page.getByRole('option').filter({has:page.locator('strong',{hasText:/^재조사$/})}).click();await page.getByRole('option').filter({hasText:'재조사 ·'}).first().click();await page.getByLabel('조사 요청',{exact:true}).fill('만년필을 다시 찾아줘. 총예산은 1달러 이하, 하한은 0.50달러로 바꿔.');await page.getByRole('button',{name:'조사 요청 보내기',exact:true}).click();let after;for(let i=0;i<90;i++){after=await work();const round=after.research.groups[0]?.round;if(round?.roundNumber>prev&&['RESULTS_READY','NO_RESULTS','FAILED'].includes(round.status)&&!after.activeWork)break;await page.waitForTimeout(1500);}await fs.writeFile(out+'/new-round.json',JSON.stringify(after,null,2));assert.equal(after.research.groups[0].round.status,'RESULTS_READY');assert.equal(after.catalogResearch.pools.find(p=>p.targetId===pen).products.length,1);console.log('PASS new budget round',after.research.groups[0].round.roundNumber,after.catalogResearch.pools.find(p=>p.targetId===pen).products.map(p=>({source:p.source,price:p.priceRange})));
// APPEND snapshots use the current budget and same-key replay ignores subsequent edits.
await patch({kind:'SET_TARGET',targetId:pen,amount:'40.00',quantity:2,updateMinimum:true});await page.reload();const appendResponse=page.waitForResponse(r=>r.url().endsWith('/catalog-research/expansions')&&r.request().method()==='POST',{timeout:60000});await page.locator('.catalog-ui-target').first().getByRole('button',{name:'후보 더 찾기',exact:true}).click();const result=await appendResponse;const body=await result.json();assert.equal(result.status(),200,JSON.stringify(body));const req=result.request(),savedRequest=req.postDataJSON(),key=req.headers()['idempotency-key'];await patch({kind:'SET_TARGET',targetId:pen,amount:'60.00',quantity:2,updateMinimum:true});const replay=await c.request.post(req.url(),{headers:{'Idempotency-Key':key},data:savedRequest});assert.equal(replay.status(),200,JSON.stringify(await replay.json()));assert.equal((await replay.json()).replay,true);await fs.writeFile(out+'/append.json',JSON.stringify({key,body,replay:await replay.json()},null,2));console.log('PASS APPEND current budget and durable replay');
// Remove ink atomically and leave headphones available for manual review.
await page.reload();let old=await budget();const removed=old.allocations[1],target=(await work()).targets.find(t=>t.id===removed.targetId);await page.getByRole('button',{name:target.title+' 상품 제거',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'제거',exact:true}).click();await page.getByRole('alertdialog').waitFor({state:'hidden'});const now=await budget();assert.deepEqual(now.allocations,old.allocations.filter(a=>a.targetId!==removed.targetId));assert.equal(Math.round(Number(now.totalAmount)*100),Math.round((Number(old.totalAmount)-Number(removed.amount))*100));console.log('PASS UI Target removal derives total');
await fs.writeFile(out+'/more-result.json',JSON.stringify({id,errors,ledger:now,checks:['lost_response','overbudget_cart','new_round','append_replay','remove']},null,2));assert.deepEqual(errors,[]);
}finally{await browser.close();}
}

async function localeAndInit() {
const browser=await firefox.launch();const c=await browser.newContext({viewport:{width:1440,height:1000}});const page=await c.newPage();page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await c.request.post(base+'/api/v1/dev/auth/session',{data:{profileKey:'empty-user'}});const cap=await(await c.request.get(base+'/api/v1/managed-runner/capability')).json();
async function prefs(locale){const v=await(await c.request.get(base+'/api/v1/me/preferences')).json();assert.equal((await c.request.patch(base+'/api/v1/me/preferences',{data:{schemaVersion:'vitlane.user-preferences.v1',expectedVersion:v.preferences.version,uiLocale:locale,preferredCurrency:'USD',researchCountry:'US'}})).status(),200);}
await prefs('ko-KR');
// Actual Init UI defaults to No limit and always exposes budget settings.
await page.goto(base+'/');await page.getByRole('button',{name:'예산 설정',exact:true}).click();assert.equal(await page.getByLabel('총 예산',{exact:true}).inputValue(),'');assert.equal(await page.getByLabel('초기 배분 방식',{exact:true}).isDisabled(),true);await page.getByRole('button',{name:'취소',exact:true}).click();await page.locator('#curation-intent').fill('만년필과 노이즈 캔슬링 헤드폰 추천');await page.locator('.shell-intent-composer__submit').click();await page.waitForURL(/\/curations\//);const id=page.url().split('/').pop(),url=base+'/curations/'+id,bp=base+`/api/v1/curations/${id}/budget`;
await fs.writeFile(out+'/review-curation-id',id);const budget=async()=>await(await c.request.get(bp)).json();const work=async()=>await(await c.request.get(base+`/api/v1/curations/${id}/workspace`)).json();let w;for(let i=0;i<100;i++){w=await work();if(w.targets?.length===2&&!w.activeWork&&w.research.groups.every(g=>g.round.status==='RESULTS_READY'))break;await page.waitForTimeout(1500);}assert.equal(w.targets.length,2);let b=await budget();assert.equal(b.enabled,false);assert.equal(b.totalAmount,null);assert(b.allocations.every(a=>a.amount===null));await page.reload();await page.locator('.curation-budget__bar').waitFor();console.log('PASS real AI Init None');
// Enable from existing TargetSet with equal distribution; cancel Auto while still preparing.
await page.locator('.curation-budget__heading button').first().click();await page.getByLabel('총 예산',{exact:true}).fill('300.01');let held;await page.route('**/budget/proposals',async route=>{held=route;});await page.getByRole('button',{name:'배분하기',exact:true}).click();await page.getByRole('button',{name:'취소',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});if(held)await held.fulfill({status:503,json:{error:{code:'TEST_PROPOSAL_CANCEL'}}});await page.unroute('**/budget/proposals');assert.equal((await budget()).enabled,false);
await page.locator('.curation-budget__heading button').first().click();await page.getByLabel('총 예산',{exact:true}).fill('300.01');await page.getByRole('button',{name:'배분하기',exact:true}).click();await page.getByRole('button',{name:'균등 배분',exact:true}).click();await page.getByRole('button',{name:'저장',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});b=await budget();assert.deepEqual(b.allocations.map(a=>a.amount),['150.01','150.00']);console.log('PASS canceled Auto draft and existing Equal enable');
// Real AI equal Init does not change total by rounding.
const r=await c.request.post(base+'/api/v1/shopping-plans',{headers:{'Idempotency-Key':randomUUID()},data:{originalIntent:'만년필과 잉크 추천',planningMode:'AUTO',executionMode:'EXPERIMENT',budget:{schemaVersion:'vitlane.curation-budget.v1',currency:'USD',totalAmount:'100.01',allocationMode:'EQUAL'},location:{country:'US',city:''},category:'',allowedItems:[],blockedItems:[],referenceUrl:'',urlMode:'NONE',agentMode:'MANAGED',modelKey:cap.defaultModelKey}});assert.equal(r.status(),201);const equalID=(await r.json()).curation.id;let equal;for(let i=0;i<90;i++){equal=await(await c.request.get(base+`/api/v1/curations/${equalID}/budget`)).json();if(equal.allocations?.length===2)break;await page.waitForTimeout(1500);}assert.equal(equal.totalAmount,'100.01');assert.deepEqual(equal.allocations.map(a=>a.amount),['50.01','50.00']);console.log('PASS real AI Init Equal');
// Localization and layout, no edits during projection checks.
const expected=await budget();for(const locale of ['en-US','ko-KR']){await prefs(locale);await page.goto(url);await page.locator('.curation-budget__heading button').first().waitFor();await page.waitForFunction(()=>document.querySelectorAll('.budget-delta').length>=2);await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:out+'/'+locale+'-desktop.png',fullPage:true});for(const zoom of [1,2]){await page.setViewportSize({width:320,height:900});await page.evaluate(z=>{document.documentElement.style.fontSize=`${16*z}px`;window.dispatchEvent(new Event('resize'));},zoom);await page.locator('.curation-budget__heading button').first().click();await page.getByLabel(locale==='ko-KR'?'총 예산':'Total budget',{exact:true}).waitFor();await page.waitForTimeout(350);await page.screenshot({path:out+'/'+locale+'-320-'+zoom+'x-budget.png',fullPage:true});let size=await page.evaluate(()=>({page:document.documentElement.scrollWidth,viewport:innerWidth,dialog:document.querySelector('[role="dialog"]').getBoundingClientRect().toJSON(),scroll:document.querySelector('[role="dialog"]').scrollWidth}));assert(size.page<=size.viewport+1,JSON.stringify(size));assert(size.dialog.x>=0&&size.dialog.right<=321,JSON.stringify(size));assert(size.scroll<=size.dialog.width+1,JSON.stringify(size));await page.keyboard.press('Tab');assert(await page.getByRole('dialog').evaluate(d=>d.contains(document.activeElement)));await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});await page.locator('.curation-budget__segment').first().click();await page.waitForTimeout(350);await page.screenshot({path:out+'/'+locale+'-320-'+zoom+'x-target.png',fullPage:true});await page.keyboard.press('Escape');}assert.deepEqual(await budget(),expected);await page.evaluate(()=>document.documentElement.style.fontSize='16px');}
await fs.writeFile(out+'/matrix-result.json',JSON.stringify({id,url,equalID,checks:['InitNone','InitEqual','cancelAuto','enableEqual','EnglishKorean','320px','200percent','focus','views_do_not_save'],errors},null,2));assert.deepEqual(errors,[]);console.log('PASS locale mobile matrix',url);
}finally{await browser.close();}
}

(async()=>{await initialScenario();await budgetEditing();await researchAndCart();await localeAndInit();})().catch(error=>{console.error(error);process.exitCode=1;});
