#!/usr/bin/env bash
set -euo pipefail

contracts_root="$(cd "$(dirname "$0")/.." && pwd)"
repository_root="$(cd "${contracts_root}/.." && pwd)"
output_root="${repository_root}/shared/onchain/abi/v1"
server_output="${repository_root}/server/internal/ordering/payment/giwa/infra/evm/zz_generated_abi.go"
web_output="${repository_root}/web/src/shared/onchain/abi.ts"
deployment_index="${contracts_root}/deployments/91342/index.json"
consumer_deployment="${repository_root}/shared/onchain/deployments/91342.json"

mkdir -p "${output_root}"

export_abi() {
  local contract_name="$1"
  local source_path="$2"
  local artifact="${contracts_root}/out/${contract_name}.sol/${contract_name}.json"
  local output="${output_root}/${contract_name}.json"
  local artifact_sha256

  if [[ ! -f "${artifact}" ]]; then
    echo "missing Foundry artifact: ${artifact}" >&2
    exit 1
  fi

  # Foundry's top-level artifact id is assigned from the local compilation graph and
  # is not stable across tool installations. Hash only the canonical compilation
  # payload that consumers and reviewers depend on.
  artifact_sha256="$(
    jq --compact-output --sort-keys \
      '{
        abi,
        bytecode,
        deployedBytecode,
        methodIdentifiers,
        metadata
      }' "${artifact}" \
      | sha256sum \
      | cut -d ' ' -f 1
  )"

  jq --sort-keys \
    --arg contract_name "${contract_name}" \
    --arg source "contracts/src/${source_path}.sol" \
    --arg artifact_sha256 "${artifact_sha256}" \
    '{
      schemaVersion: "vitlane.contract-abi.v1",
      contractName: $contract_name,
      source: $source,
      compiler: .metadata.compiler.version,
      artifactSha256: $artifact_sha256,
      abi: .abi
    }' "${artifact}" > "${output}"
}

export_abi "VitlaneTestUSD" "token/VitlaneTestUSD"
export_abi "VitlaneFaucet" "faucet/VitlaneFaucet"
export_abi "VitlaneSettlement" "settlement/VitlaneSettlement"

{
  printf '%s\n' '// Code generated by contracts/script/export-artifacts.sh; DO NOT EDIT.'
  printf '%s\n\n' 'package evm'
  printf '%s' 'const tokenABIJSON = `'
  jq --compact-output '.abi' "${output_root}/VitlaneTestUSD.json"
  printf '%s\n\n' '`'
  printf '%s' 'const faucetABIJSON = `'
  jq --compact-output '.abi' "${output_root}/VitlaneFaucet.json"
  printf '%s\n\n' '`'
  printf '%s' 'const settlementABIJSON = `'
  jq --compact-output '.abi' "${output_root}/VitlaneSettlement.json"
  printf '%s\n' '`'
} > "${server_output}"

{
  printf '%s\n' '// Generated by contracts/script/export-artifacts.sh; DO NOT EDIT.'
  printf 'export const testUSDABI = %s as const;\n\n' \
    "$(jq --compact-output '.abi' "${output_root}/VitlaneTestUSD.json")"
  printf 'export const faucetABI = %s as const;\n\n' \
    "$(jq --compact-output '.abi' "${output_root}/VitlaneFaucet.json")"
  printf 'export const settlementABI = %s as const;\n' \
    "$(jq --compact-output '.abi' "${output_root}/VitlaneSettlement.json")"
} > "${web_output}"

active_version="$(jq -er '.activeVersion' "${deployment_index}")"
active_manifest="${contracts_root}/deployments/91342/${active_version}.json"
if [[ "$(jq -r '.status' "${active_manifest}")" != "ACTIVE" ]]; then
  echo "active deployment index points to a non-ACTIVE manifest" >&2
  exit 1
fi
mkdir -p "$(dirname "${consumer_deployment}")"
jq --sort-keys '{
  schemaVersion: "vitlane.onchain-consumer-deployment.v1",
  version,
  environment,
  chainId,
  contracts: (
    .contracts
    | with_entries(
        .value |= {
          address,
          runtimeBytecodeHash
        }
      )
  )
}' "${active_manifest}" > "${consumer_deployment}"
