-- Business-card intent keys are generated by trusted owner adapters. Keep
-- them in a persistence namespace that arbitrary customer/operator message
-- keys cannot reserve.
ALTER TABLE support_messages
    ADD COLUMN idempotency_namespace TEXT NOT NULL DEFAULT 'EXTERNAL'
        CHECK (idempotency_namespace IN ('EXTERNAL','BUSINESS_CARD'));

UPDATE support_messages
SET idempotency_namespace='BUSINESS_CARD'
WHERE content_kind='BUSINESS_CARD';

ALTER TABLE support_messages
    DROP CONSTRAINT support_messages_idempotency_key_key;

CREATE UNIQUE INDEX uq_support_messages_idempotency_namespace_key
    ON support_messages(idempotency_namespace, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

ALTER TABLE support_messages
    ADD CONSTRAINT support_messages_idempotency_namespace_shape_check CHECK (
        (content_kind='TEXT' AND idempotency_namespace='EXTERNAL')
        OR
        (content_kind='BUSINESS_CARD' AND idempotency_namespace='BUSINESS_CARD')
    );

ALTER TABLE support_messages
    DROP CONSTRAINT support_messages_content_shape_check;

ALTER TABLE support_messages
    ADD CONSTRAINT support_messages_content_shape_check CHECK (
        (content_kind='TEXT' AND author IN ('CUSTOMER','OPERATOR')
         AND business_card_type IS NULL AND business_reference_type IS NULL
         AND business_reference_id IS NULL AND action_required=FALSE
         AND resolves_card_id IS NULL AND public_payload IS NULL)
        OR
        (content_kind='BUSINESS_CARD'
         AND business_card_type IN (
            'PROCUREMENT_REQUEST','PROCUREMENT_RESPONSE','PROCUREMENT_DECISION',
            'ORDER_CANCELLATION','REFUND_REQUEST','REFUND_DECISION','REFUND_STATUS',
            'PAYPAL_DISPUTE','PAYPAL_DISPUTE_STATUS',
            'DELIVERY_DELAY','DELIVERY_RESOLUTION')
         AND business_reference_type IN (
            'PROCUREMENT','REFUND','PAYPAL_DISPUTE','DELIVERY')
         AND ((business_reference_type='PROCUREMENT' AND business_card_type IN (
                'PROCUREMENT_REQUEST','PROCUREMENT_RESPONSE','PROCUREMENT_DECISION',
                'ORDER_CANCELLATION'))
           OR (business_reference_type='REFUND' AND business_card_type IN (
                'REFUND_REQUEST','REFUND_DECISION','REFUND_STATUS'))
           OR (business_reference_type='PAYPAL_DISPUTE' AND business_card_type IN (
                'PAYPAL_DISPUTE','PAYPAL_DISPUTE_STATUS'))
           OR (business_reference_type='DELIVERY' AND business_card_type IN (
                'DELIVERY_DELAY','DELIVERY_RESOLUTION')))
         AND char_length(business_reference_id) BETWEEN 1 AND 160
         AND jsonb_typeof(public_payload)='object'
         AND octet_length(public_payload::text) <= 32768
         AND NOT (action_required AND resolves_card_id IS NOT NULL))
    );

-- Owner facts are the durable queue. A NULL marker means the typed Support
-- projection must be retried; the marker is written only after idempotent
-- publication succeeds. This avoids a second cross-product transaction and
-- survives a crash immediately after the owner transaction commits.
ALTER TABLE agency_order_refund_requests
    ADD COLUMN support_request_notified_at TIMESTAMPTZ,
    ADD COLUMN support_decision_notified_at TIMESTAMPTZ;

-- Do not turn historical terminal reviews into a one-time customer message
-- blast at cutover. Open reviews stay NULL so the worker can selectively
-- reconstruct the currently active request, and their future decision remains
-- deliverable.
UPDATE agency_order_refund_requests
SET support_request_notified_at=created_at,
    support_decision_notified_at=updated_at
WHERE state='RESOLVED';

CREATE INDEX idx_refund_requests_support_request_pending
    ON agency_order_refund_requests(created_at, id)
    WHERE support_request_notified_at IS NULL;

CREATE INDEX idx_refund_requests_support_decision_pending
    ON agency_order_refund_requests(updated_at, id)
    WHERE state='RESOLVED' AND support_decision_notified_at IS NULL;

ALTER TABLE procurement_decision_records
    ADD COLUMN support_notified_at TIMESTAMPTZ;

-- Historical operator evidence remains queryable in Procurement itself. It is
-- not retroactively emitted into the customer conversation.
UPDATE procurement_decision_records
SET support_notified_at=created_at;

CREATE INDEX idx_procurement_decisions_support_pending
    ON procurement_decision_records(created_at, id)
    WHERE support_notified_at IS NULL;

ALTER TABLE procurement_customer_requests
    ADD COLUMN support_request_notified_at TIMESTAMPTZ,
    ADD COLUMN support_resolution_notified_at TIMESTAMPTZ;

-- Only requests that still require a customer response are reconstructed.
-- Terminal historical request/response pairs are treated as observed at their
-- owner timestamps to avoid stale action cards and notification spam.
UPDATE procurement_customer_requests
SET support_request_notified_at=requested_at,
    support_resolution_notified_at=updated_at
WHERE state<>'PENDING';

CREATE INDEX idx_procurement_requests_support_request_pending
    ON procurement_customer_requests(requested_at, id)
    WHERE support_request_notified_at IS NULL;

CREATE INDEX idx_procurement_requests_support_resolution_pending
    ON procurement_customer_requests(updated_at, id)
    WHERE state<>'PENDING' AND support_resolution_notified_at IS NULL;

ALTER TABLE logistics_delivery_resolutions
    ADD COLUMN support_notified_at TIMESTAMPTZ;

UPDATE logistics_delivery_resolutions
SET support_notified_at=created_at;

CREATE INDEX idx_delivery_resolutions_support_pending
    ON logistics_delivery_resolutions(created_at, id)
    WHERE support_notified_at IS NULL;

ALTER TABLE agency_order_cancellations
    ADD COLUMN support_notified_at TIMESTAMPTZ;

UPDATE agency_order_cancellations
SET support_notified_at=created_at;

CREATE INDEX idx_order_cancellations_support_pending
    ON agency_order_cancellations(created_at, id)
    WHERE support_notified_at IS NULL;
