package domain

import "errors"

var (
	ErrIntentRequired                     = errors.New("INTENT_REQUIRED")
	ErrExecutionModeInvalid               = errors.New("EXECUTION_MODE_INVALID")
	ErrBudgetNonPositive                  = errors.New("BUDGET_NON_POSITIVE")
	ErrPriceRangeInvalid                  = errors.New("PRICE_RANGE_INVALID")
	ErrLiveCountryUnsupported             = errors.New("LIVE_COUNTRY_UNSUPPORTED")
	ErrURLModeInvalid                     = errors.New("URL_MODE_INVALID")
	ErrTargetIncomplete                   = errors.New("TARGET_INCOMPLETE")
	ErrPlanNotEditable                    = errors.New("PLAN_NOT_EDITABLE")
	ErrVersionConflict                    = errors.New("VERSION_CONFLICT")
	ErrPlanNotFound                       = errors.New("PLAN_NOT_FOUND")
	ErrPlanNotConfirmed                   = errors.New("PLAN_NOT_CONFIRMED")
	ErrCurationNotFound                   = errors.New("CURATION_NOT_FOUND")
	ErrCurationPhaseInvalid               = errors.New("CURATION_PHASE_INVALID")
	ErrCurationArchived                   = errors.New("CURATION_ARCHIVED")
	ErrCurationTargetsRequired            = errors.New("CURATION_TARGETS_REQUIRED")
	ErrCurationActionInvalid              = errors.New("CURATION_ACTION_INVALID")
	ErrCurationActionTypeInvalid          = errors.New("CURATION_ACTION_TYPE_INVALID")
	ErrCurationActionPhaseInvalid         = errors.New("CURATION_ACTION_PHASE_INVALID")
	ErrCurationActionUnavailable          = errors.New("CURATION_ACTION_UNAVAILABLE")
	ErrCurationActionInProgress           = errors.New("CURATION_ACTION_IN_PROGRESS")
	ErrCurationActionCommandInvalid       = errors.New("CURATION_ACTION_COMMAND_INVALID")
	ErrCurationActionAliasUnknown         = errors.New("CURATION_ACTION_ALIAS_UNKNOWN")
	ErrCurationActionBodyInvalid          = errors.New("CURATION_ACTION_BODY_INVALID")
	ErrCurationActionSubjectInvalid       = errors.New("CURATION_ACTION_SUBJECT_INVALID")
	ErrCurationActionVersionInvalid       = errors.New("CURATION_ACTION_VERSION_INVALID")
	ErrCurationActionNotAppendable        = errors.New("CURATION_ACTION_NOT_APPENDABLE")
	ErrTargetNotFound                     = errors.New("TARGET_NOT_FOUND")
	ErrIdempotencyKeyRequired             = errors.New("IDEMPOTENCY_KEY_REQUIRED")
	ErrIdempotencyKeyReused               = errors.New("IDEMPOTENCY_KEY_REUSED")
	ErrPlanningModeInvalid                = errors.New("PLANNING_MODE_INVALID")
	ErrAgentModeInvalid                   = errors.New("AGENT_MODE_INVALID")
	ErrExternalAgentRetired               = errors.New("EXTERNAL_AGENT_RETIRED")
	ErrPlanningRequired                   = errors.New("PLANNING_REQUIRED")
	ErrPlanningTaskNotFound               = errors.New("PLANNING_TASK_NOT_FOUND")
	ErrPlanningTaskClosed                 = errors.New("PLANNING_TASK_CLOSED")
	ErrPlanningContextStale               = errors.New("PLANNING_CONTEXT_STALE")
	ErrProposalInvalid                    = errors.New("PLANNING_PROPOSAL_INVALID")
	ErrProposalIDInvalid                  = errors.New("PROPOSAL_ID_INVALID")
	ErrProposalSchemaInvalid              = errors.New("PROPOSAL_SCHEMA_INVALID")
	ErrTargetCountInvalid                 = errors.New("TARGET_COUNT_INVALID")
	ErrTargetBudgetInvalid                = errors.New("TARGET_BUDGET_INVALID")
	ErrTargetSetMismatch                  = errors.New("TARGET_SET_MISMATCH")
	ErrSingleTargetRequired               = errors.New("SINGLE_TARGET_REQUIRED")
	ErrCurationRunNotFound                = errors.New("CURATION_RUN_NOT_FOUND")
	ErrCurationRunClosed                  = errors.New("CURATION_RUN_CLOSED")
	ErrExpansionUnavailable               = errors.New("CURATION_EXPANSION_UNAVAILABLE")
	ErrExpansionInstruction               = errors.New("EXPANSION_INSTRUCTION_REQUIRED")
	ErrTargetRemovalBlocked               = errors.New("TARGET_REMOVAL_BLOCKED")
	ErrExpansionInProgress                = errors.New("CURATION_EXPANSION_IN_PROGRESS")
	ErrTooManyActiveActions               = errors.New("CURATION_TOO_MANY_ACTIVE_ACTIONS")
	ErrActionNotCancellable               = errors.New("CURATION_ACTION_NOT_CANCELLABLE")
	ErrAgentResearchDerivationUnavailable = errors.New(
		"AGENT_RESEARCH_DERIVATION_UNAVAILABLE",
	)
)
